CREATE  --> Insert
READ    --> leer
UPDATE  --> actu+alziar
DELETE  --> borrar
*/

-- revisar el entorno de trabajo
.version
.database
.show

.tables

DROP TABLE LOCALIDAD;

CREATE TABLE LOCALIDAD
(
     IDLOCALIDAD        INTEGER PRIMARY KEY AUTOINCREMENT
    ,HID                INTEGER 
    ,NOMBRE             VARCHAR (100) NOT NULL
    ,ESTADO             VARCHAR(1) NOT NULL DEFAULT('A')
    ,IDLOCALIDADTIPO    INTEGER 
);

INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (1, NULL,"PAIS", NULL);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (2, 1,"PROVINCIA",NULL);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (3, 2,"CANTON",NULL);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (4, 3,"ZONA",NULL);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (5, 4,"CIUDAD",NULL);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, IDLOCALIDADTIPO) 
            VALUES (6, 5,"PARROQUIA",NULL);

INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (7, NULL, "COLOMBIA",'A' , 1);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (8, NULL, "ECUADOR",'A' , 1);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (9, 7, "TOLIMA",'A' , 2);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (10, 8, "PICHINCHA",'A' , 2);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (11, 10, "QUITO",'A', 3);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (12, 10, "RUMIÑAHUI",'A' , 3);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (13, 11, "ZONA 7",'A' , 4);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (14, 11, "ZONA 8",'A' , 4);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (15, 7, "ANTIOQUIA",'A' , 2);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (16, 7, "CAUCA",'A' , 2);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (17, 15, "SAN JERÓNIMO",'A', 3);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (18, 16, "POPAYAN",'A' , 3);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (19, 18, "ZONA 2",'A' , 4);
INSERT INTO LOCALIDAD (IDLOCALIDAD, HID, NOMBRE, ESTADO, IDLOCALIDADTIPO) VALUES (20, 18, "ZONA 3",'A' , 4);

SELECT * FROM LOCALIDAD;
